# Repaso de Listas

In [1]:
b = [1,2,3]

Aplicando Operadores Matemáticos a Listas

In [2]:
b + b + [4,-2]

[1, 2, 3, 1, 2, 3, 4, -2]

In [3]:
b * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

Solución? For Loops?

In [4]:
for elemento in b:
    print(elemento)

1
2
3


In [5]:
for elemento in b:
    print(elemento + elemento)

2
4
6


Y si lo quiero guardar en otra variable (por ejemplo 'c = b+b')?

Una forma es:
* Definir una lista vacio
* recorrer todos los elementos en b
* sumarlos entre si y meterlos dentro de una lista ([elemento + elemento])
* sumar esta lista a 'c' (**c \+= algo** es lo mismo que **c = c + algo**)

In [6]:
c = []
for elemento in b:
    c += [elemento + elemento]
c

[2, 4, 6]

In [7]:
c = []
for elemento in b:
    c += [elemento * 4]
c

[4, 8, 12]

Alternativa??

# Librería Numpy

Es el paquete de arrays mas comunmente usado en Python. La diferencia entre un array y una lista nativa es que el array es continuo en memoria mientras que la lista esta encadenada, haciendo que el array sea mucho mas rapido de leer y, por tanto, la estructura de datos natural para el procesamiento de grandes cantidades de datos

In [1]:
import numpy as np

In [22]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [20]:
type(arr1)

numpy.ndarray

In [21]:
arr1.shape

(4, 1)

In [23]:
arr1 + arr1

array([2, 4, 6, 8])

In [24]:
arr1 / arr1

array([1., 1., 1., 1.])

In [25]:
arr1 + 100

array([101, 102, 103, 104])

## Dimensiones

Los arrays de numpy pueden ser unidimensionales (1D), bidimensionales (2D) o cuantas dimensiones quieran.


In [29]:
np.random.rand(3,5)

array([[0.33665459, 0.33767202, 0.63009958, 0.53733596, 0.16726119],
       [0.56985189, 0.61613419, 0.16452916, 0.26305235, 0.736514  ],
       [0.42986643, 0.44980695, 0.10212578, 0.68768191, 0.84670854]])

In [30]:
data = np.round( np.random.rand(3,5) * 100 )

In [31]:
data

array([[ 9., 72., 96., 25., 77.],
       [46., 68., 49., 88., 45.],
       [53., 40., 96., 29., 77.]])

In [32]:
data * 2

array([[ 18., 144., 192.,  50., 154.],
       [ 92., 136.,  98., 176.,  90.],
       [106.,  80., 192.,  58., 154.]])

Tamaño de 'data'

In [33]:
data.shape

(3, 5)

## Indexado

El indexado en los ndarray funciona igual que el indexado de listas

Los elementos de una ndarray se pueden acceder mediante su indice

* Todos los indices empiezan en 0
* Se usan numeros enteros
* El indice maximo equivale a la (cantidad de elementos - 1)
* Se accede al elemento con *indice*
* Si el indice es negativo, se cuenta desde el final
* Se puede hacer "slicing" con rangos de indices separados por dos puntos (:)
* Se pueden usar indices negativos que cuentan desde atrás pero empezando en -1

In [34]:
arr1[0]

1

In [35]:
arr1[3]

4

In [36]:
arr1[len(arr1)]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [37]:
arr1[len(arr1) - 1]

4

In [38]:
arr1[-1]

4

In [39]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [40]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr2d[:1]

array([[1, 2, 3]])

In [45]:
arr2d[:1, 0:2]

array([[1, 2]])

In [27]:
arr2d[1, :2]

array([4, 5])

In [28]:
arr2d[:, 1]

array([2, 5, 8])

## Funciones de agregación

Suelen expresarse como métodos del objeto array. En general, tienen como consecuencia disminuir las dimensiones del arreglo y son muy utilizados en matemáticas y física. <br>
La siguiente tabla muestra los más utilizados, puede encontrar la documentación [aquí](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#calculation).

| Operación | Descripción |
|:----------|:------------|
| `a.sum()`    | Retorna la suma del arreglo en el eje dado |
| `a.min()`    | Retorna el valor mínimo de un eje |
| `a.mean()`   | Retorna la media aritmética en un eje dado |
| `a.var()`    | Retorna la varianza en un eje dado|
| `a.std()`    | Retorna la desviación estándar en un eje dado |
| `a.prod()`   | Retorna el producto en un eje dado |
| `a.argmin()` | Retorna el índice donde ocurren los valores mínimos de cada eje |
| `a.ptp()`    | Valor pico a pico en un eje |
| `a.conj()`   | Retorna el conjugado complejo de todos los elementos |
| `a.round()`  | Retorna el valor redondeado de cada elemento |
| `a.trace()`  | Retorna la suma de las diagonales del arreglo |
| `a.argmax()` | Retorna el índice donde ocurren los valores máximos de cada eje |
| `a.cumsum()` | Retorna la suma acumulativa en un eje dado |
| `a.cumprod()`| Retorna el producto acumulativo en un eje dado |

In [29]:
arr1.mean()

2.5

In [30]:
arr1.std()

1.118033988749895

In [48]:
arr2d.shape

(3, 3)

In [47]:
arr2d.size

9

In [49]:
arr2 = np.ones((2, 3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
arr1.argmax()

3

In [35]:
arr2.shape

(2, 3)

In [36]:
arr2.size

6

In [37]:
len(arr2)

2

## Funciones universales

Son funciones optimizadas que operan sobre el array. Dificilmente vamos a necesitar hacer algo que no este ya implementado, la lista completa de funciones universales en este [enlace](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#math-operations)

### Funciones para crear ndarrays

Hay muchas formas de crear arreglos en Numpy, puede explorarlas todas en este [enlace](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html). Las más comunes son:

| Función | Descripción |
|:--------|:------------|
| `empty` | Arreglo vacio |
| `zeros` | Arreglo de ceros |
| `ones`  | Arreglo de unos |
| `full`  | Se especifica un valor para llenar todo el arreglo con él |
| `identity` | Unos en la diagonal y cero en el resto |
| `array` | Constructor genérico |
| `fromfunction` | Según una función dada que retorna un valor para cada punto de la coordenada |
| `loadtxt` | Carga los datos de un archivo |

In [38]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.full([2,5], fill_value=10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

# Ejercicios



1.   Crear un array de 100 números aleatorios con valores de -100 a +100. 







In [4]:
array1=np.random.rand(100)*200-100
print(array1)

[ 86.01057728 -48.54700825  80.33888074 -53.88050289  -0.16304987
  35.7562857  -93.92854088 -31.02706543  39.78392568  95.12459184
 -37.72257847  87.44351018  53.12370041  26.46750359  62.60124248
  57.34599718   1.99792361 -90.87535998 -25.59915516  66.46942096
   5.47426915 -82.75429481   3.24170448  26.02461026  -1.74989084
  54.85511339  45.83223913 -89.74116128 -97.18778674   8.45084503
 -28.46963835  50.39318588  94.08118996 -87.9936446  -10.39001742
 -16.31094822 -11.35706617  42.65881948  41.74529843 -55.6603982
  -8.04832161  91.3813894  -45.59023056  31.63729561 -53.63104701
   0.1349397  -68.62677782  52.87158314  64.86612595  12.88335406
 -48.66799931  38.58381116 -33.34203165 -93.79986754 -89.07927988
  67.81344477  26.50532235  93.69540348 -36.98234072  28.7328203
   6.49671192  46.92307807  77.50440587  13.18969637  59.98644134
  15.34442386  15.08684422  88.22987711 -72.56916328 -11.34222741
 -55.90306869  54.99201894  43.00621874  39.58792313 -29.15173189
 -60.0007115


2.   Usando arrays de booleanos crear otros 3 arrays que contengan los positivos, los negativos y los mayores de 50 de ese array.

In [7]:
array1[array1<0]

array([-48.54700825, -53.88050289,  -0.16304987, -93.92854088,
       -31.02706543, -37.72257847, -90.87535998, -25.59915516,
       -82.75429481,  -1.74989084, -89.74116128, -97.18778674,
       -28.46963835, -87.9936446 , -10.39001742, -16.31094822,
       -11.35706617, -55.6603982 ,  -8.04832161, -45.59023056,
       -53.63104701, -68.62677782, -48.66799931, -33.34203165,
       -93.79986754, -89.07927988, -36.98234072, -72.56916328,
       -11.34222741, -55.90306869, -29.15173189, -60.00071151,
       -39.25479465, -33.38641936, -78.78492927, -55.48227956,
       -80.06397432, -98.88967962, -80.55460857, -32.36591185])

In [8]:
array1[array1>0]

array([86.01057728, 80.33888074, 35.7562857 , 39.78392568, 95.12459184,
       87.44351018, 53.12370041, 26.46750359, 62.60124248, 57.34599718,
        1.99792361, 66.46942096,  5.47426915,  3.24170448, 26.02461026,
       54.85511339, 45.83223913,  8.45084503, 50.39318588, 94.08118996,
       42.65881948, 41.74529843, 91.3813894 , 31.63729561,  0.1349397 ,
       52.87158314, 64.86612595, 12.88335406, 38.58381116, 67.81344477,
       26.50532235, 93.69540348, 28.7328203 ,  6.49671192, 46.92307807,
       77.50440587, 13.18969637, 59.98644134, 15.34442386, 15.08684422,
       88.22987711, 54.99201894, 43.00621874, 39.58792313, 14.17646124,
       81.22140201, 59.31013229, 97.49891444, 48.15432095, 58.72963904,
       55.89542318, 95.6659721 , 39.19121062, 46.84179788, 12.09315344,
        3.30029881, 56.17961215, 19.28172229,  2.80876214, 24.02731177])

In [9]:
array1[array1>50]

array([86.01057728, 80.33888074, 95.12459184, 87.44351018, 53.12370041,
       62.60124248, 57.34599718, 66.46942096, 54.85511339, 50.39318588,
       94.08118996, 91.3813894 , 52.87158314, 64.86612595, 67.81344477,
       93.69540348, 77.50440587, 59.98644134, 88.22987711, 54.99201894,
       81.22140201, 59.31013229, 97.49891444, 58.72963904, 55.89542318,
       95.6659721 , 56.17961215])

3.   Crear un array bidimensional 5x5 con todos los valores cero. Usando el indexado de arrays, asigna 1 a todos los elementos de la última fila y 5 a todos los elementos de la primera columna. Finalmente, asigna el valor 100 a todos los elementos del subarray central 3x3 de la matriz de 5x5.

In [15]:
matriz=np.zeros((5,5))
print(matriz)
print()
matriz[-1,:]=1
print(matriz)
print()
matriz[:,0]=5
print(matriz)
print()
matriz[1:4,1:4]=100
print(matriz)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]

[[5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [5. 1. 1. 1. 1.]]

[[  5.   0.   0.   0.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  5. 100. 100. 100.   0.]
 [  5.   1.   1.   1.   1.]]


4.   Crear una matriz de 10 x 3 con valores aleatorios entre cero y uno



In [20]:
np.random.randint(low=0,high=2, size=(10, 3))

array([[1, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 1],
       [0, 0, 1]])


5.   Buscar el valor mínimo de la matriz

In [22]:
matriz.min()

0.0

6.   Buscar la posición (indice) del valor mínimo de la matriz

In [23]:
np.where(matriz==0)

(array([0, 0, 0, 0, 1, 2, 3]), array([1, 2, 3, 4, 4, 4, 4]))